[packages.homebrew]
[packages.homebrew.common]
casks = [
    "1password",
    "1password-cli",
    "flux",
    "ghostty",
    "git-credential-manager",
    "obsidian",
    "rectangle-pro",
]
formulae = [
    "atuin",       # Better shell history
    "coreutils",
    "fd",
    "fish",
    "fzf",
    "git",
    "jq",
    "neovim",
    "mise",
    "ripgrep",
    "ssh-copy-id",
    "starship",
    "uv",
    "zoxide",
]
