[settings]
idiomatic_version_file_enable_tools = ["node","python"]

[settings.python]
compile = false

[tools]
go = "latest"
golangci-lint = "2.6.1"
jq = "1.8.1"
python = "3.14"
shellcheck = "latest"
shfmt = "latest"
